In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import os
#Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cross_validation import cross_val_score, cross_val_predict, KFold
from sklearn.pipeline import make_pipeline
from pylab import rcParams

%matplotlib inline
params = {'axes.labelsize': 14,'axes.titlesize':14, 'text.fontsize': 14, 'legend.fontsize': 14,
          'xtick.labelsize': 13, 'ytick.labelsize': 14}
rcParams['figure.figsize'] = 6.5, 4

matplotlib.rcParams.update(params)

/home/marleen/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/marleen/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py:913: UserWarning: text.fontsize is deprecated and replaced with font.size; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))

In [2]:
data = pd.read_csv('Data Mining VU data/training_set_VU_DM_2014.csv')

FileNotFoundError: File b'Data Mining VU data/training_set_VU_DM_2014.csv' does not exist

In [ ]:
df = data.head(100)
data.head(100)

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,...,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
0,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,893,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,10404,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,21315,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
3,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,27348,2,4.0,...,NaN,NaN,NaN,NaN,-1.0,0.0,5.0,0,NaN,0
4,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,29604,4,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
5,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,30184,4,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,7.0,0,NaN,0
6,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,44147,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
7,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,50984,2,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
8,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,53341,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,6.0,0,NaN,0
9,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,56880,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
10,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,59267,3,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
11,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,59526,3,3.5,...,NaN,NaN,NaN,NaN,1.0,0.0,31.0,0,NaN,0
12,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,68914,2,3.0,...,NaN,NaN,NaN,NaN,0.0,0.0,11.0,1,114.29,1
13,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,74474,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
14,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,81437,3,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
15,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,85728,2,3.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
16,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,88096,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,15.0,0,NaN,0
17,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,88127,3,3.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
18,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,88218,4,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
19,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,89073,4,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,5.0,0,NaN,0
20,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,95166,3,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
21,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,95307,4,3.5,...,NaN,NaN,NaN,NaN,-1.0,0.0,27.0,0,NaN,0
22,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,97247,2,3.5,...,NaN,NaN,NaN,NaN,-1.0,0.0,5.0,0,NaN,0
23,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,107872,2,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,14.0,0,NaN,0
24,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,111000,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
25,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,111106,3,2.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
26,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,114766,2,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
27,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,122844,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
28,4,2012-12-31 08:59:22,5,219,NaN,NaN,219,3625,4,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
29,4,2012-12-31 08:59:22,5,219,NaN,NaN,219,11622,4,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,32491,3,4.5,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0,NaN,0
71,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,33805,3,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
72,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,35397,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
73,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,39137,2,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
74,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,41497,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
75,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,54403,2,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
76,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,58176,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
77,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,63511,3,4.5,...,NaN,NaN,NaN,NaN,0.0,1.0,NaN,0,NaN,0
78,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,66444,4,4.5,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0,NaN,0
79,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,67150,4,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
80,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,73738,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
81,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,83293,3,4.5,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0,NaN,0
82,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,90151,5,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
83,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,119302,3,3.5,...,NaN,NaN,NaN,NaN,0.0,1.0,NaN,0,NaN,0
84,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,125655,3,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
85,8,2013-03-20 17:50:44,5,219,NaN,NaN,219,134607,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
86,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,6492,2,4.0,...,NaN,NaN,NaN,NaN,1.0,0.0,12.0,0,NaN,0
87,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,8946,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
88,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,9952,2,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
89,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,19470,2,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
90,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,20499,2,3.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1,NaN,0
91,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,24526,3,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
92,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,26421,3,5.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
93,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,27675,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
94,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,28364,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
95,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,33980,3,5.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
96,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,35021,3,4.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
97,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,38443,3,4.0,...,NaN,NaN,NaN,NaN,-1.0,0.0,10.0,0,NaN,0
98,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,47116,3,4.5,...,NaN,NaN,NaN,NaN,0.0,0.0,11.0,0,NaN,0
99,11,2013-02-25 08:39:33,5,219,NaN,NaN,219,59898,3,0.0,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0

#  Feature Engineering

### Calculate correlation and mutual information/information gain

In [ ]:
g = sns.pairplot(df, palette = 'seismic',size=1.2,diag_kind = 'kde',diag_kws=dict(shade=True),plot_kws=dict(s=10) )
g.set(xticklabels=[])

In [ ]:
plt.matshow(df.corr())